# Generated by Django 5.1.2 on 2024-11-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_cusregistartion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cusregistartion',
            new_name='customer_reg',
        ),
    ]
