# Generated by Django 5.1.2 on 2024-11-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_tbl_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_review',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.tbl_book'),
        ),
    ]
