# Generated by Django 5.1.2 on 2024-11-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_tbl_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_review',
            name='review',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_key', models.CharField(max_length=100, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.tbl_book')),
            ],
        ),
    ]
